
---
title: "Example of using nlrx package"
author: "Leonardo A. Saravia"
date: "9/3/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

needed_packages <- c(
    "tidyverse"
  , "lubridate"
  , "nlrx")

lapply(needed_packages, function(x) { if(!require(x,character.only = TRUE)) install.packages(x)} )

theme_set(theme_bw())
source("R/functions.r")

#
# NetLogo 
# Setup for nlrx
#

if( Sys.info()['nodename'] =="ls-pro") {
  simfolder <- "/home/leonardo/Academicos/GitProjects/pollinatorsNL"

} else if(Sys.info()['nodename'] =="biologia2018") {                     # Server UNGS
  simfolder <- "/home/leonardo/GitProjects/pollinatorsNL"
}


#
# Setup for nlrx
#
# Unix default NetLogo installation path (adjust to your needs!):
#
netlogopath <- file.path("/home/leonardo/NetLogo")
modelpath <- file.path(simfolder, "plant_pollinator_landscapes02.nlogo")
outpath <- file.path(simfolder,"Simulations")

# If not defined set the JAVA version of your local 
if(Sys.getenv("JAVA_HOME")==""){
  Sys.setenv(JAVA_HOME = "/usr/lib/jvm/java-11-openjdk-amd64")
  ## "/usr/lib/jvm/java-8-oracle"
}

nl <- nl(nlversion = "6.2",
         nlpath = netlogopath,
         modelpath = modelpath,
         jvmmem = 2048)


```

# Make experiment simulations using nlrx

* In "variables" we setup
  1. Different pollinators parameter files
  2. Different plant parameter files
  3. Different values for seed-percent

["land-cover-classes" 5]
["landscape_type" "Random natural"]
["active-search" true]

["number-of-days" 1]
["Video" false]
["nlrx-experiment" ""]
["generate-output-file" true]
["pol-parameters-file-name" "Parameters/pollinator_parametersEx1.csv"]
["plant-parameters-file-name" "Parameters/plant_parametersEx1.csv"]
["seed-percent" 1.0E-5]

```{r gen_fit_lhs, echo=FALSE, tidy=TRUE, message=FALSE, warning=FALSE, eval=TRUE}

polfiles <- paste0("\"Parameters/", list.files("Parameters/", "^poll.*\\.csv$"),"\"")
polfiles <- polfiles[-1]
plantfiles <- paste0("\"Parameters/",list.files("Parameters/", "^plant.*\\.csv$"),"\"")
plantfiles <- plantfiles[-1]

nl@experiment <- experiment(expname="RandomNaturalEx1Ex2",
                            outpath=outpath,
                            repetition=1,
                            tickmetrics="false",
                            idsetup="setup",
                            idgo="go",
                            runtime=0,
                            idrunnum="nlrx-experiment",
                            metrics=c("count pollinators"),
                            variables = list("pol-parameters-file-name" = list(values=polfiles),
                                             "plant-parameters-file-name" = list(values=plantfiles),
                                              "seed-percent" = list(values=c(1e-05,1))),
                            constants = list("land-cover-classes" = 5,
                                               "landscape_type" = "\"Random natural\"",
                                               "active-search"= "true",
                                               "number-of-days" = 1,
                                               "generate-output-file"= "true",
                                               "Video" = "false"
                                             ))

#
# Run full factorial 10 times (nseeds=10)
#

nl@simdesign <- simdesign_ff(nl=nl,
                               nseeds=3)


# 
# run in Paralell 
# Here the setup for the cluster should be done
#
require(future)
plan(multisession)
require(tictoc)
tic()                                 # to measure how much time it takes 
results <- run_nl_all(nl,split = 8)   # this number increases with the number of cores here I am using 24 cores (3 nseeds x 8 combinations)
toc()                                 # the simulations took 1119 sec = 19 min
plan(sequential)
names(results)

#
# Write the output 
#
setsim(nl, "simoutput") <- results 
write_simoutput(nl)
```

