
---
title: "Example of reading simulations from behaviorspace"
author: "Leonardo A. Saravia"
date: "21/5/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

needed_packages <- c(
    "tidyverse"
  , "lubridate")

lapply(needed_packages, function(x) { if(!require(x,character.only = TRUE)) install.packages(x)} )

theme_set(theme_bw())

source("R/functions.r")
```

# Run and Read simulations from behaviorspace (headless)

```{r read_behav, echo=FALSE, tidy=TRUE, message=FALSE, warning=FALSE, eval=FALSE}

# Execute simulations - Probably not work outside linux
#
system("bash netlogo-headless-exp.sh")

# Read the names of simulation files generated
#
simul_fn <- list.files(path="Simulations",pattern="^Visits.*csv")

# Read the habitat parameters file
#
hab_parms <- read_delim("Simulations/Run_habitat_parameters.csv",";",col_names = FALSE)
colnames(hab_parms) <- c("simul_fn","landscape_type","land_cover_classes", "seed_percent", "habitat_proportions","mean_free_path")

# Read all simulations in simul_fn and merge with the info in habitat parameters file
#
mdl <- lapply( simul_fn, function(x){ 
  ff <- read_delim(paste0("Simulations/",x),";") %>% mutate(simul_fn=paste0("Simulations/",x)) %>% inner_join(hab_parms)
  })
mdl <- bind_rows(mdl)

# Correct names
#
names(mdl) <- str_trim(names(mdl))

# Some stats
#
#
mdl %>% group_by(seed_percent,pollinator_species) %>% summarize(foraging_distance = mean(foraging_distance) ) 

# Total Number of visits 
#
mdl %>% group_by(seed_percent,pollinator_species,plant_species) %>% summarize(number_visits = n() ) 


# Calculate mean habitat proportion
#
hab_parms <- hab_parms %>% rowwise() %>% mutate( 
  mean_hab_prop = mean(as.numeric(unlist(str_split(str_sub(habitat_proportions, 2, str_length(habitat_proportions) -1 ), " ")))),
  overall_mean_free_path = mean(as.numeric(unlist(str_split(str_sub(mean_free_path, 2, str_length(mean_free_path) -1 ), " "))))
                                                 )

 
# 
#

#Analyse data
#
# where n_visits is the number of visits to the same plant
names(mdl)
# To get consecutive visits of individual pollinators to the same plant species (don't need plant_patch)
#
# Here testing for one pollinator if the pattern is rigth
test <- mdl %>% filter( seed_percent==1e-05,run==0,pollinator_agent==31)

# To get consecutive visits of individual pollinators to the same plant species 
# 
res <- mdl %>% group_by(seed_percent, run, pollinator_species,plant_species,pollinator_agent) %>% summarize(n_visits=n()) %>% filter(n_visits>1)


# To get visits to the same plant species by pollinator species 
#
res <- mdl %>% group_by(seed_percent, pollinator_species,plant_species) %>% summarize(n_visits=n()) %>% filter(n_visits>1)

# foraging distances of by pollinator species
#
res <- mdl %>% group_by( seed_percent,run,pollinator_species, pollinator_agent) %>% select(seed_percent,run,day,plant_species, pollinator_species, plant_patch,pollinator_agent,foraging_distance) %>% mutate( plant_foraging_distance = foraging_distance - lag(foraging_distance)) %>% mutate(plant_foraging_distance=if_else(is.na(plant_foraging_distance) | plant_foraging_distance<0, foraging_distance, plant_foraging_distance )
) # %>% arrange(seed_percent,run,pollinator_species, pollinator_agent)

ggplot(res, aes(x=plant_foraging_distance,color=factor(pollinator_species))) + geom_histogram(aes(y=..density..), fill="white")+
 geom_density(alpha=.2, fill="#FF6666") + facet_wrap( ~pollinator_species) + scale_x_log10() + scale_color_viridis_d(guide=FALSE)

```

